# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My blog'
description: 'This is my new blog'
permalink: pretty

# Pagination
paginate: 5
paginate_path: page:num

# Collections
collections:
  posts:
    title: Strange and Unusual
    output: true
    description: "a personal archive of sorts"
